name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - riscv32imc-esp-espidf
          - xtensa-esp32-espidf
        idf-version:
          - release/v4.4
          - release/v5.0

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: true
      - uses: Swatinem/rust-cache@v2
      - name: Build
        env:
          ESP_IDF_VERSION: ${{ matrix.idf-version }}
          RUSTFLAGS: "${{ matrix.idf-version == 'release/v5.0' && '--cfg espidf_time64' || ''}}"
        run: cargo build --target ${{ matrix.target }} --verbose --examples
      - name: Fmt check
        run: cargo fmt --check
      - name: Clippy check
        env:
          ESP_IDF_VERSION: ${{ matrix.idf-version }}
          RUSTFLAGS: "${{ matrix.idf-version == 'release/v5.0' && '--cfg espidf_time64' || ''}}"
        run: cargo clippy --target ${{ matrix.target }} --all-features -- -D clippy::all -W clippy::nursery
